name: Documentation

on:
  push:
    branches:
      - splink3
    paths:
      - "**.md"
      - "mkdocs.yml"
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocstrings==0.18.1 mkdocstrings-python==0.6.6 mkdocstrings-python-legacy==0.2.2 mkdocs-semiliterate==0.3.0
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy
