name: docswithmkdoc

on:
  push:
    branches:
      - splink3
    paths:
      - "**.md"
      - "mkdocs.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install --upgrade pip && pip install mkdocs==1.1.2 mknotebooks mkdocs-material==7.3.1 mkdocs-gen-files mkdocs-autorefs==0.4.1 mkdocs-gen-files==0.3.4 mkdocs-include-markdown-plugin==3.2.3 mkdocs-material==7.3.6 mkdocs-material-extensions==1.0.3 mkdocs-mermaid2-plugin==0.5.2 mkdocs-monorepo-plugin==1.0.1 mkdocs-semiliterate==0.3.0 mkdocs-simple-plugin==1.1.0 mkdocstrings==0.18.1 mkdocstrings-python==0.6.6 mkdocstrings-python-legacy==0.2.2 mkdocs-semiliterate==0.3.0
      - run: mkdocs gh-deploy --force
      - run: mkdocs --version
