name: docswithmkdoc

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - splink4_dev_build
    paths:
      # files that affect the docs build:
      - docs/**
      - CONTRIBUTING.md
      - mkdocs.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install docs dependencies
        run: |
          pip install --upgrade pip
          pip install -r scripts/docs-requirements.txt

      - name: build documentation
        run: mkdocs build

      - name: check links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
          args: --offline site/ --verbose './**/*.html'

      - name: Upload built site
        uses: actions/upload-artifact@v3
        with:
          name: built_site
          path: site

      # some environment info:
      - run: pip freeze
      - run: mkdocs --version

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # we only deplot on push to master
    # this job doesn't run if this is triggered by a PR
    if: github.event_name == 'push'
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: built_site
          path: site

      - name: commit and force-push to gh-pages branch
        run: |
          pip install ghp-import==2.1.0
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          ghp-import -opfm "Update docs from commit ${{ github.sha }}" site
