name: new_docs

on:
  push:
    branches:
      - splink4_dev_build
    paths:
      - docs/**
      - CONTRIBUTING.md
      - mkdocs.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install docs dependencies
        run: |
          pip install --upgrade pip
          pip install -r scripts/docs-requirements.txt

      - name: build documentation
        run: mkdocs build
